version: '3.8'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
